var training_il = [['1.ext.train', 'Message', {'hideProgressBar': 'true', 'html': '<p>On the next screen you will see a practice scenario of four sentences <b>with markup</b>.</p><p>These sentences will NOT contain sufficient information to determine the who/what/when/where of the terrorist plot, but go ahead and make your best guess so that you can practice entering and submitting you answer.</p><p>Again, this is only a practice scenario. Feel free to take as much time as you need.</p> ', 'countsForProgressBar': 'false'}], ['1.ext.train', 'MessageFormC', {'hideProgressBar': 'true', 'html': {'include': 'train.ext.html'}, 'answers': {'include': 'train.ans.html'}, 'countsForProgressBar': 'false'}], ['1.ext.train', 'Message', {'html': {'include': 'train.confirm.html'}}], ['1.ext.train', 'Message', {'hideProgressBar': 'true', 'html': '<p>You have completed the training scenario. The experiment will now begin, and you will be shown two full scenarios with markup.</p><p>Remember to work as quickly as you can without sacrificing accuracy.</p>', 'countsForProgressBar': 'false'}], ['2.orig.train', 'Message', {'html': '<p>On the next screen you will see a practice scenario of four sentences <b>without markup</b>.</p><p>These sentences will NOT contain sufficient information to determine the who/what/when/where of the terrorist plot, but go ahead and make your best guess so that you can practice entering and submitting you answer.</p><p>Again, this is only a practice scenario. Feel free to take as much time as you need.</p> '}], ['2.orig.train', 'MessageFormC', {'hideProgressBar': 'true', 'html': {'include': 'train.orig.html'}, 'answers': {'include': 'train.ans.html'}, 'countsForProgressBar': 'false'}], ['2.orig.train', 'Message', {'html': {'include': 'train.confirm.html'}}], ['2.orig.train', 'Message', {'hideProgressBar': 'true', 'html': '<p>You have completed the training scenario. The experiment will now begin, and you will be shown two full scenarios without markup.</p><p>Remember to work as quickly as you can without sacrificing accuracy.</p>', 'countsForProgressBar': 'false'}]];

var training_li = [['2.ext.train', 'Message', {'hideProgressBar': 'true', 'html': '<p>On the next screen you will see a practice scenario of four sentences <b>with markup</b>.</p><p>These sentences will NOT contain sufficient information to determine the who/what/when/where of the terrorist plot, but go ahead and make your best guess so that you can practice entering and submitting you answer.</p><p>Again, this is only a practice scenario. Feel free to take as much time as you need.</p> ', 'countsForProgressBar': 'false'}], ['2.ext.train', 'MessageFormC', {'hideProgressBar': 'true', 'html': {'include': 'train.ext.html'}, 'answers': {'include': 'train.ans.html'}, 'countsForProgressBar': 'false'}], ['2.ext.train', 'Message', {'html': {'include': 'train.confirm.html'}}], ['2.ext.train', 'Message', {'hideProgressBar': 'true', 'html': '<p>You have completed the training scenario. The experiment will now begin, and you will be shown two full scenarios with markup.</p><p>Remember to work as quickly as you can without sacrificing accuracy.</p>', 'countsForProgressBar': 'false'}], ['1.orig.train', 'Message', {'html': '<p>On the next screen you will see a practice scenario of four sentences <b>without markup</b>.</p><p>These sentences will NOT contain sufficient information to determine the who/what/when/where of the terrorist plot, but go ahead and make your best guess so that you can practice entering and submitting you answer.</p><p>Again, this is only a practice scenario. Feel free to take as much time as you need.</p> '}], ['1.orig.train', 'MessageFormC', {'hideProgressBar': 'true', 'html': {'include': 'train.orig.html'}, 'answers': {'include': 'train.ans.html'}, 'countsForProgressBar': 'false'}], ['1.orig.train', 'Message', {'html': {'include': 'train.confirm.html'}}], ['1.orig.train', 'Message', {'hideProgressBar': 'true', 'html': '<p>You have completed the training scenario. The experiment will now begin, and you will be shown two full scenarios without markup.</p><p>Remember to work as quickly as you can without sacrificing accuracy.</p>', 'countsForProgressBar': 'false'}]];

var p1_il = [['1.ext.Scenario1', 'MessageFormC', {'html': {'include': 'Scenario1.ext.html'}, 'answers': {'include': 'Scenario1.ans.html'}}], ['1.ext.Scenario8', 'MessageFormC', {'html': {'include': 'Scenario8.ext.html'}, 'answers': {'include': 'Scenario8.ans.html'}}], ['2.orig.Scenario4', 'MessageFormC', {'html': {'include': 'Scenario4.orig.html'}, 'answers': {'include': 'Scenario4.ans.html'}}], ['2.orig.Scenario7', 'MessageFormC', {'html': {'include': 'Scenario7.orig.html'}, 'answers': {'include': 'Scenario7.ans.html'}}]];

var p1_li = [['2.ext.Scenario1', 'MessageFormC', {'html': {'include': 'Scenario1.ext.html'}, 'answers': {'include': 'Scenario1.ans.html'}}], ['2.ext.Scenario8', 'MessageFormC', {'html': {'include': 'Scenario8.ext.html'}, 'answers': {'include': 'Scenario8.ans.html'}}], ['1.orig.Scenario4', 'MessageFormC', {'html': {'include': 'Scenario4.orig.html'}, 'answers': {'include': 'Scenario4.ans.html'}}], ['1.orig.Scenario7', 'MessageFormC', {'html': {'include': 'Scenario7.orig.html'}, 'answers': {'include': 'Scenario7.ans.html'}}]];

var p2_il = [['1.ext.Scenario4', 'MessageFormC', {'html': {'include': 'Scenario4.ext.html'}, 'answers': {'include': 'Scenario4.ans.html'}}], ['1.ext.Scenario7', 'MessageFormC', {'html': {'include': 'Scenario7.ext.html'}, 'answers': {'include': 'Scenario7.ans.html'}}], ['2.orig.Scenario1', 'MessageFormC', {'html': {'include': 'Scenario1.orig.html'}, 'answers': {'include': 'Scenario1.ans.html'}}], ['2.orig.Scenario8', 'MessageFormC', {'html': {'include': 'Scenario8.orig.html'}, 'answers': {'include': 'Scenario8.ans.html'}}]];

var p2_li = [['2.ext.Scenario4', 'MessageFormC', {'html': {'include': 'Scenario4.ext.html'}, 'answers': {'include': 'Scenario4.ans.html'}}], ['2.ext.Scenario7', 'MessageFormC', {'html': {'include': 'Scenario7.ext.html'}, 'answers': {'include': 'Scenario7.ans.html'}}], ['1.orig.Scenario1', 'MessageFormC', {'html': {'include': 'Scenario1.orig.html'}, 'answers': {'include': 'Scenario1.ans.html'}}], ['1.orig.Scenario8', 'MessageFormC', {'html': {'include': 'Scenario8.orig.html'}, 'answers': {'include': 'Scenario8.ans.html'}}]];

var p3_il = [['1.ext.Scenario4', 'MessageFormC', {'html': {'include': 'Scenario4.ext.html'}, 'answers': {'include': 'Scenario4.ans.html'}}], ['1.ext.Scenario8', 'MessageFormC', {'html': {'include': 'Scenario8.ext.html'}, 'answers': {'include': 'Scenario8.ans.html'}}], ['2.orig.Scenario1', 'MessageFormC', {'html': {'include': 'Scenario1.orig.html'}, 'answers': {'include': 'Scenario1.ans.html'}}], ['2.orig.Scenario7', 'MessageFormC', {'html': {'include': 'Scenario7.orig.html'}, 'answers': {'include': 'Scenario7.ans.html'}}]];

var p3_li = [['2.ext.Scenario4', 'MessageFormC', {'html': {'include': 'Scenario4.ext.html'}, 'answers': {'include': 'Scenario4.ans.html'}}], ['2.ext.Scenario8', 'MessageFormC', {'html': {'include': 'Scenario8.ext.html'}, 'answers': {'include': 'Scenario8.ans.html'}}], ['1.orig.Scenario1', 'MessageFormC', {'html': {'include': 'Scenario1.orig.html'}, 'answers': {'include': 'Scenario1.ans.html'}}], ['1.orig.Scenario7', 'MessageFormC', {'html': {'include': 'Scenario7.orig.html'}, 'answers': {'include': 'Scenario7.ans.html'}}]];

var p4_il = [['1.ext.Scenario1', 'MessageFormC', {'html': {'include': 'Scenario1.ext.html'}, 'answers': {'include': 'Scenario1.ans.html'}}], ['1.ext.Scenario7', 'MessageFormC', {'html': {'include': 'Scenario7.ext.html'}, 'answers': {'include': 'Scenario7.ans.html'}}], ['2.orig.Scenario4', 'MessageFormC', {'html': {'include': 'Scenario4.orig.html'}, 'answers': {'include': 'Scenario4.ans.html'}}], ['2.orig.Scenario8', 'MessageFormC', {'html': {'include': 'Scenario8.orig.html'}, 'answers': {'include': 'Scenario8.ans.html'}}]];

var p4_li = [['2.ext.Scenario1', 'MessageFormC', {'html': {'include': 'Scenario1.ext.html'}, 'answers': {'include': 'Scenario1.ans.html'}}], ['2.ext.Scenario7', 'MessageFormC', {'html': {'include': 'Scenario7.ext.html'}, 'answers': {'include': 'Scenario7.ans.html'}}], ['1.orig.Scenario4', 'MessageFormC', {'html': {'include': 'Scenario4.orig.html'}, 'answers': {'include': 'Scenario4.ans.html'}}], ['1.orig.Scenario8', 'MessageFormC', {'html': {'include': 'Scenario8.orig.html'}, 'answers': {'include': 'Scenario8.ans.html'}}]];

var p5_il = [['1.ext.Scenario7', 'MessageFormC', {'html': {'include': 'Scenario7.ext.html'}, 'answers': {'include': 'Scenario7.ans.html'}}], ['1.ext.Scenario8', 'MessageFormC', {'html': {'include': 'Scenario8.ext.html'}, 'answers': {'include': 'Scenario8.ans.html'}}], ['2.orig.Scenario1', 'MessageFormC', {'html': {'include': 'Scenario1.orig.html'}, 'answers': {'include': 'Scenario1.ans.html'}}], ['2.orig.Scenario4', 'MessageFormC', {'html': {'include': 'Scenario4.orig.html'}, 'answers': {'include': 'Scenario4.ans.html'}}]];

var p5_li = [['2.ext.Scenario7', 'MessageFormC', {'html': {'include': 'Scenario7.ext.html'}, 'answers': {'include': 'Scenario7.ans.html'}}], ['2.ext.Scenario8', 'MessageFormC', {'html': {'include': 'Scenario8.ext.html'}, 'answers': {'include': 'Scenario8.ans.html'}}], ['1.orig.Scenario1', 'MessageFormC', {'html': {'include': 'Scenario1.orig.html'}, 'answers': {'include': 'Scenario1.ans.html'}}], ['1.orig.Scenario4', 'MessageFormC', {'html': {'include': 'Scenario4.orig.html'}, 'answers': {'include': 'Scenario4.ans.html'}}]];

var p6_il = [['1.ext.Scenario1', 'MessageFormC', {'html': {'include': 'Scenario1.ext.html'}, 'answers': {'include': 'Scenario1.ans.html'}}], ['1.ext.Scenario4', 'MessageFormC', {'html': {'include': 'Scenario4.ext.html'}, 'answers': {'include': 'Scenario4.ans.html'}}], ['2.orig.Scenario7', 'MessageFormC', {'html': {'include': 'Scenario7.orig.html'}, 'answers': {'include': 'Scenario7.ans.html'}}], ['2.orig.Scenario8', 'MessageFormC', {'html': {'include': 'Scenario8.orig.html'}, 'answers': {'include': 'Scenario8.ans.html'}}]];

var p6_li = [['2.ext.Scenario1', 'MessageFormC', {'html': {'include': 'Scenario1.ext.html'}, 'answers': {'include': 'Scenario1.ans.html'}}], ['2.ext.Scenario4', 'MessageFormC', {'html': {'include': 'Scenario4.ext.html'}, 'answers': {'include': 'Scenario4.ans.html'}}], ['1.orig.Scenario7', 'MessageFormC', {'html': {'include': 'Scenario7.orig.html'}, 'answers': {'include': 'Scenario7.ans.html'}}], ['1.orig.Scenario8', 'MessageFormC', {'html': {'include': 'Scenario8.orig.html'}, 'answers': {'include': 'Scenario8.ans.html'}}]];

var comments_il = [['1.ext.comments', 'Form', {'html': "Any comments or feedback you'd like to provide?<br><textarea name='comments' rows='4' cols='50'></textarea>"}], ['2.orig.comments', 'Form', {'html': "Any comments or feedback you'd like to provide?<br><textarea name='comments' rows='4' cols='50'></textarea>"}]];


var comments_li = [['2.ext.comments', 'Form', {'html': "Any comments or feedback you'd like to provide?<br><textarea name='comments' rows='4' cols='50'></textarea>"}], ['1.orig.comments', 'Form', {'html': "Any comments or feedback you'd like to provide?<br><textarea name='comments' rows='4' cols='50'></textarea>"}]];


var ss1_il = seq('inst', '1.ext.train', followEachWith('test-after',shuffle('1.ext.Scenario1', '1.ext.Scenario8')), '1.ext.comments', 'middle', '2.orig.train', followEachWith('test-after',shuffle('2.orig.Scenario4', '2.orig.Scenario7')), '2.orig.comments', 'end');

var ss1_li = seq('inst', '1.orig.train', followEachWith('test-after',shuffle('1.orig.Scenario4', '1.orig.Scenario7')), '1.orig.comments', 'middle', '2.ext.train', followEachWith('test-after',shuffle('2.ext.Scenario1', '2.ext.Scenario8')), '2.ext.comments', 'end');

var ss2_il = seq('inst', '1.ext.train', followEachWith('test-after',shuffle('1.ext.Scenario4', '1.ext.Scenario7')), '1.ext.comments', 'middle', '2.orig.train', followEachWith('test-after',shuffle('2.orig.Scenario1', '2.orig.Scenario8')), '2.orig.comments', 'end');

var ss2_li = seq('inst', '1.orig.train', followEachWith('test-after',shuffle('1.orig.Scenario1', '1.orig.Scenario8')), '1.orig.comments', 'middle', '2.ext.train', followEachWith('test-after',shuffle('2.ext.Scenario4', '2.ext.Scenario7')), '2.ext.comments', 'end');

var ss3_il = seq('inst', '1.ext.train', followEachWith('test-after',shuffle('1.ext.Scenario4', '1.ext.Scenario8')), '1.ext.comments', 'middle', '2.orig.train', followEachWith('test-after',shuffle('2.orig.Scenario1', '2.orig.Scenario7')), '2.orig.comments', 'end');

var ss3_li = seq('inst', '1.orig.train', followEachWith('test-after',shuffle('1.orig.Scenario1', '1.orig.Scenario7')), '1.orig.comments', 'middle', '2.ext.train', followEachWith('test-after',shuffle('2.ext.Scenario4', '2.ext.Scenario8')), '2.ext.comments', 'end');

var ss4_il = seq('inst', '1.ext.train', followEachWith('test-after',shuffle('1.ext.Scenario1', '1.ext.Scenario7')), '1.ext.comments', 'middle', '2.orig.train', followEachWith('test-after',shuffle('2.orig.Scenario4', '2.orig.Scenario8')), '2.orig.comments', 'end');

var ss4_li = seq('inst', '1.orig.train', followEachWith('test-after',shuffle('1.orig.Scenario4', '1.orig.Scenario8')), '1.orig.comments', 'middle', '2.ext.train', followEachWith('test-after',shuffle('2.ext.Scenario1', '2.ext.Scenario7')), '2.ext.comments', 'end');

var ss5_il = seq('inst', '1.ext.train', followEachWith('test-after',shuffle('1.ext.Scenario7', '1.ext.Scenario8')), '1.ext.comments', 'middle', '2.orig.train', followEachWith('test-after',shuffle('2.orig.Scenario1', '2.orig.Scenario4')), '2.orig.comments', 'end');

var ss5_li = seq('inst', '1.orig.train', followEachWith('test-after',shuffle('1.orig.Scenario1', '1.orig.Scenario4')), '1.orig.comments', 'middle', '2.ext.train', followEachWith('test-after',shuffle('2.ext.Scenario7', '2.ext.Scenario8')), '2.ext.comments', 'end');

var ss6_il = seq('inst', '1.ext.train', followEachWith('test-after',shuffle('1.ext.Scenario1', '1.ext.Scenario4')), '1.ext.comments', 'middle', '2.orig.train', followEachWith('test-after',shuffle('2.orig.Scenario7', '2.orig.Scenario8')), '2.orig.comments', 'end');

var ss6_li = seq('inst', '1.orig.train', followEachWith('test-after',shuffle('1.orig.Scenario7', '1.orig.Scenario8')), '1.orig.comments', 'middle', '2.ext.train', followEachWith('test-after',shuffle('2.ext.Scenario1', '2.ext.Scenario4')), '2.ext.comments', 'end');

